### ISSUE TITLE
Example gbl_SUT

### ISSUE THREAD

**Issue by jha92** [beam-telescopes/eutelescope#4]
Hi,
just pushed a first version of an [example of gbl_SUT](https://github.com/beam-telescopes/eutelescope/tree/dev_example_gblSUT/jobsub/examples/gbl_SUT) in a new [branch](https://github.com/beam-telescopes/eutelescope/tree/dev_example_gblSUT/).
Would be nice, if @dreyling can also test it (I need to do this, too)!
As base version to add I chose "new jobsub+submitCondor".

**Comment by dreyling** [comment]
I just have a quick look on it, and one first question, how/where the SUT.xml is used?

**Comment by jha92** [comment]
Should be hopefully explained in the README. But the idea is to include it manually before the gblkinkestimator. It is tidious and not very handy, but due to the missing functionality of ExcludePlanes it is the current way to go...

**Comment by TCThenna** [comment]
just quickly some comments

https://github.com/beam-telescopes/eutelescope/blob/4a557a12784e9cb44e70057d563131c8145f5964/processors/src/EUTelTripletGBLKinkEstimator.cc#L498

the factor 5 should probably be removed in order to use the exact value specified in the config.
or, as previously discussed in another issue, we should have 2 parameters for downstream and upstream slope.

I see that the TTree will hold the values from the triplet kink estimates, but not the GBL kinks, is that correct? If yes, the GBL kinks should be added, too.
that is:
in x: aCorr[5]+acorr[7]
in y: aCorr[6]+acorr[8]

https://github.com/beam-telescopes/eutelescope/blob/4a557a12784e9cb44e70057d563131c8145f5964/processors/src/EUTelTripletGBLKinkEstimator.cc#L680
The X_0 is hardcoded for aluminium. If that should also work automatically, the X0 of the material should be read from an xml.

I'll also have a closer look later.

**Comment by TCThenna** [comment]
I added this extra vector planePosActive, which I thought would be needed so one can loop over all planes (active and inactive), but maybe, this can be erased and the functionality can be replaced using the planeID.

I dont think these 2 variables are used (and if they are, they should be renamed):
https://github.com/beam-telescopes/eutelescope/blob/4a557a12784e9cb44e70057d563131c8145f5964/processors/src/EUTelTripletGBLKinkEstimator.cc#L642-L643

In the gblutility, there is a histo plotting all triplet-driplet-candiates distances during matching. Here, one could make a histo of those that are from final tracks.

**Comment by jha92** [comment]
GBLKinkEstimator not anymore in use.
